site_name: rekx
repo_url: https://github.com/NikosAlexandris/rekx
repo_name: NikosAlexandris/rekx
edit_uri: edit/main/docs/

nav:
  - Overview:
      - Overview: index.md
      - To Do: to_do.md
  - Installation: install/install.md
  - How To:
      - Help?: how_to/help.md
      - Diagnose: how_to/diagnose.md
      - Suggest: how_to/suggest.md
      - Rechunk: how_to/rechunk.md
      - Identify appropriate structure: how_to/chunking_parameterisation.md
      - Kerchunk to JSON: how_to/kerchunk_to_json.md
      - Kerchunk to Parquet: how_to/kerchunk_to_parquet.md
  - Tutorials:
      - SARAH3: tutorials/sarah3/chunking_sarah3_time_series.md
      - External file: tutorials/sarah3/sarah3_sid_time_variables.md
      - Massive JSON Kerchunking: tutorials/massive_json_kerchunking.md
  - Reference:
      - Overview: reference/reference.md
      - Notes: reference/notes.md
      - Concepts: reference/concepts.md
      - Kerchunking large time series : reference/kerchunking.md
      - Xarray: reference/xarray.md
  - About: 
      - Meta: about/meta.md
  - References: references/references.md
  - License: license.md

theme:
  icon:
    logo: material/animation-outline
  palette:
    - primary: lime
    - accent: deep purple
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  custom_dir: docs/overrides
  features:
    - content.action.edit
    - content.action.view
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    # - navigation.indexes 
    - toc.follow
    - toc.integrate 
    - navigation.top

plugins:
  - search
  - tags:
      tags_file: includes/tags.md

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      pygments_lang_class: true
      linenums: true
      line_spans: __span
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - docs/includes
