site_name: rekx
repo_url: https://github.com/NikosAlexandris/rekx
repo_name: NikosAlexandris/rekx
edit_uri: edit/main/docs/
# Keep this in sync with pyproject.toml and index.md
site_description: rekx dynamically interfaces Kerchunk and informs on chunked data structures
site_author: Nikos Alexandris
copyright: Copyright &copy; 2023 Nikos Alexandris. Licensed under the EUPL-1.2 or later

watch:
  - docs/includes

nav:
  - Overview:
      - '': index.md
      - To Do: to_do.md
  - Installation: install/install.md
  - How To:
      - how_to/index.md
      - Diagnose: how_to/diagnose.md
      - Suggest: how_to/suggest.md
      - Rechunk: how_to/rechunk.md
      - Identify appropriate structure: how_to/chunking_parameterisation.md
      - Kerchunk to JSON: how_to/kerchunk_to_json.md
      - Kerchunk to Parquet: how_to/kerchunk_to_parquet.md
      - Performance: how_to/read_performance.md
  - Tutorials:
      # - SARAH3: tutorials/sarah3/chunking_sarah3_time_series.md
      # - External file: tutorials/sarah3/sarah3_sid_time_variables.md
      - Massive JSON Kerchunking: tutorials/massive_json_kerchunking.md
  - Reference:
      - Overview: reference/reference.md
      - Concepts: reference/concepts.md
      - Kerchunking: reference/kerchunking.md
      - Notes: reference/notes.md
      - Xarray: reference/xarray.md
      # - Glossary: ?
  - CLI Reference: cli/cli_reference.md
  - Meta:
      - meta/index.md
      - License: license.md
      - References: references/references.md
      - See also: references/see_also.md
  - Tags: includes/tags.md

theme:
  font:
    text: Nunito
    code: Source Code Pro
  icon:
    logo: material/animation-outline
    tag:
      concepts: simple/blueprint
      chunking: fontawesome/solid/cubes-stacked
      cli: octicons/terminal-16
      howto: material/tools
      todo: octicons/tasklist-16
      seealso: material/eye
      # html: fontawesome/brands/html5
  palette:
    - primary: lime
    - accent: deep purple
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    #
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: lime
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  name: material
  custom_dir: docs/overrides
  features:
    - search.highlight
    - search.share
    - content.tooltips
    - content.action.edit
    - content.action.view
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes 
    - toc.follow
    # - toc.integrate 
    - navigation.top
    - navigation.footer

plugins:
  - search
  - tags:
      tags_file: includes/tags.md
  - table-reader
  - exclude:
      glob:
        - "*.py"  # Python scripts
        - "*.inc"  # includes

extra:
  tags:
    Concepts: concepts
    Chunking: chunking
    CLI: cli
    How-To: howto
    To Do: todo
    See-Also: seealso

markdown_extensions:
  - toc:
      permalink: true  # Paragraph symbol linking to current headline
  - footnotes
  - def_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      pygments_lang_class: true
      linenums: true
      line_spans: __span
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - abbr
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
      check_paths: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mkdocs-typer
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
